-- R2.4 §5 - a SEGUNDA metade do provisionamento de plataforma que este repositorio nao
-- versiona, e que ninguem tinha reproduzido ainda.
--
-- POR QUE ESTE ARQUIVO EXISTE
--
-- `scripts/db-drill/00-platform-baseline.sql` reproduz o ponto cego da Onda 3: o Supabase
-- concede EXECUTE automatico em toda FUNCAO nova do schema public para anon/authenticated.
-- Aquele arquivo foi escrito para esse achado, e parou nele.
--
-- A plataforma faz a mesma coisa com TABELA, e isso nunca foi reproduzido. A primeira
-- comparacao real contra staging (run 31041870966) mediu a diferenca exata:
--
--   staging:  anon 45 grants, authenticated 45, service_role 48, postgres 48
--   efemero:  anon  3 grants, authenticated  3, service_role 48, postgres 48
--
-- 48 = 6 tabelas x 8 privilegios. A aritmetica fecha sem sobra: staging tem TUDO menos os
-- 3 INSERT que a Onda 3 revogou nas tabelas de submissao; o efemero tinha so os 3 SELECT
-- que as migrations concedem explicitamente. 45 - 3 = 42, vezes 2 papeis = as 84
-- diferencas de grant do relatorio.
--
-- A conclusao nao e sobre staging, e sobre o instrumento: as migrations deste repositorio
-- nunca precisaram CONCEDER acesso de tabela a anon, porque a plataforma ja concedia. Elas
-- so REVOGAM. Comparar contra um Postgres virgem media a ausencia da plataforma, nao o
-- estado de staging -- e 84 das 86 diferencas falavam disso.
--
-- POR QUE NAO ESTA EM 00-platform-baseline.sql
--
-- Porque aquele arquivo tambem alimenta `scripts/db-drill`, e o drill afirma hoje, em
-- 90-assertions.sql, que `anon` NAO tem INSERT em nenhuma tabela. Contra um banco virgem
-- essa afirmacao passa. Contra a plataforma de verdade ela e FALSA para markets, products
-- e prices -- e a medicao acima prova. Corrigir o drill muda uma assercao de seguranca, e
-- isso e decisao do Founder/PMO, nao efeito colateral de um PR de instrumentacao. O achado
-- esta registrado em docs/data/R2-APPLICATION-GATE.md; aqui so o instrumento de
-- equivalencia fica fiel.

-- O mecanismo real: tabela criada DEPOIS deste ponto nasce com os grants. `GRANT ALL ON
-- ALL TABLES` nao serviria -- nao existe tabela nenhuma ainda quando isto roda.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON TABLES TO anon, authenticated, service_role;
