/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoProductIdRouteImport } from './routes/produto.$productId'

const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoProductIdRoute = ProdutoProductIdRouteImport.update({
  id: '/produto/$productId',
  path: '/produto/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buscar' | '/como-funciona' | '/produto/$productId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buscar' | '/como-funciona' | '/produto/$productId'
  id: '__root__' | '/' | '/buscar' | '/como-funciona' | '/produto/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ProdutoProductIdRoute: typeof ProdutoProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$productId': {
      id: '/produto/$productId'
      path: '/produto/$productId'
      fullPath: '/produto/$productId'
      preLoaderRoute: typeof ProdutoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ProdutoProductIdRoute: ProdutoProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
