/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ParaMercadosRouteImport } from './routes/para-mercados'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProdutoProductIdRouteImport } from './routes/produto.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaMercadosRoute = ParaMercadosRouteImport.update({
  id: '/para-mercados',
  path: '/para-mercados',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoProductIdRoute = ProdutoProductIdRouteImport.update({
  id: '/produto/$productId',
  path: '/produto/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/para-mercados': typeof ParaMercadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/para-mercados': typeof ParaMercadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/para-mercados': typeof ParaMercadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/como-funciona'
    | '/para-mercados'
    | '/sitemap.xml'
    | '/produto/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/como-funciona'
    | '/para-mercados'
    | '/sitemap.xml'
    | '/produto/$productId'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/como-funciona'
    | '/para-mercados'
    | '/sitemap.xml'
    | '/produto/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ParaMercadosRoute: typeof ParaMercadosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProdutoProductIdRoute: typeof ProdutoProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-mercados': {
      id: '/para-mercados'
      path: '/para-mercados'
      fullPath: '/para-mercados'
      preLoaderRoute: typeof ParaMercadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$productId': {
      id: '/produto/$productId'
      path: '/produto/$productId'
      fullPath: '/produto/$productId'
      preLoaderRoute: typeof ProdutoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ParaMercadosRoute: ParaMercadosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProdutoProductIdRoute: ProdutoProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
